version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:latest
    container_name: diet_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongodb_data:/data/db
    networks:
      - diet_network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: diet_backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/diet_app?authSource=admin
      JWT_SECRET: your_jwt_secret_key_here
      PORT: 3001
    depends_on:
      - mongodb
    networks:
      - diet_network
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: diet_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:3001/api
      CHOKIDAR_USEPOLLING: true
    depends_on:
      - backend
    networks:
      - diet_network
    # volumes:
    #   - ./frontend:/app

volumes:
  mongodb_data:

networks:
  diet_network:
    driver: bridge